name: maybe-cpp
version: 0.2.0
homepage: https://github.com/morloclib/maybe-cpp
synopsis: C++ implementations for maybe operations
description: C++ implementations for maybe operations
category: data
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/maybe-cpp
bug-reports: https://github.com/morloclib/maybe-cpp
